    
export const USER_LOGGED_IN='USER_LOGGED_IN';
export const USER_REGISTER='USER_REGISTER';
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const LOCATION_REGISTER = "LOCATION_REGISTER";
export const CATALOGUE_REGISTER = "CATALOGUE_REGISTER";
export const PERIOD_REGISTER = "PERIOD_REGISTER";
export const RECOGNITION_REGISTER = "RECOGNITION_REGISTER"